export const edit = "EDIT",
            deleteE = "DELETE",
            save = "SAVE",
            add = "ADD",
            fetch="FETCH",
            addUser="ADD_USER",
            removeUser = "Remove_User",
            addError="ADD_ERROR",
            removeError="REMOVE_ERROR"